# Generated by Django 3.2.6 on 2021-11-11 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz', '0002_alter_userresponse_selected_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='extendeduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=20, null=True)),
                ('year', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE'), ('Others', 'Others')], default='', max_length=20, null=True)),
                ('final_score', models.IntegerField(default=0)),
                ('marking_positive', models.IntegerField(default=4)),
                ('marking_negative', models.IntegerField(default=-2)),
                ('number_of_submits', models.IntegerField(default=0)),
                ('random_ques', models.TextField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
