# Generated by Django 3.2.6 on 2021-11-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
