# Generated by Django 3.2.6 on 2021-11-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_extendeduser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='time_counter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
