# Generated by Django 3.2.6 on 2021-11-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_userlifelinedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlifelinedata',
            name='lifeline_in_use',
            field=models.IntegerField(blank=True, choices=[(1, 'Lifeline 1'), (2, 'Lifeline 2'), (3, 'Lifeline 3')], null=True),
        ),
    ]
