# Generated by Django 3.2.6 on 2021-11-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_userlifelinedata_lifeline_in_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='time_speed',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
