# Generated by Django 3.2.6 on 2021-11-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_extendeduser_time_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='red_zone_active',
            field=models.BooleanField(default=False),
        ),
    ]
