# Generated by Django 3.2.6 on 2021-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_extendeduser_correct_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='correct_ans',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='correct_ques',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
