# Generated by Django 3.2.6 on 2021-12-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_alter_extendeduser_correct_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='num_of_RZs',
            field=models.IntegerField(default=0),
        ),
    ]
