# Generated by Django 3.2.6 on 2022-01-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0014_extendeduser_num_of_rzs'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='prev_que_correct',
            field=models.BooleanField(default=False),
        ),
    ]
