# Generated by Django 3.2.6 on 2022-01-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0018_remove_extendeduser_extra_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='questions_alloted',
            field=models.BooleanField(default=False),
        ),
    ]
