# Generated by Django 3.2.6 on 2022-02-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0019_extendeduser_questions_alloted'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='level',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
