# Generated by Django 3.2.6 on 2022-02-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0020_auto_20220215_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='tab',
            field=models.IntegerField(default=4),
        ),
    ]
