# Generated by Django 3.2.6 on 2022-02-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0021_extendeduser_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='tab',
            field=models.IntegerField(default=25),
        ),
    ]
