# Generated by Django 3.2.6 on 2022-02-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0022_alter_extendeduser_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='redzone_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
