# Generated by Django 3.2.6 on 2022-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0023_extendeduser_redzone_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
    ]
