# Generated by Django 3.2.6 on 2022-02-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0025_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='tab',
            field=models.IntegerField(default=100),
        ),
    ]
