# Generated by Django 3.2.6 on 2022-03-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0027_auto_20220301_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='popLifelineModal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='popRZModal',
            field=models.BooleanField(default=False),
        ),
    ]
