# Generated by Django 3.2.6 on 2022-03-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0028_auto_20220301_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='popLifelineModal',
            new_name='isEmerLogged',
        ),
    ]
