# Generated by Django 3.2.6 on 2022-04-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0029_rename_poplifelinemodal_extendeduser_isemerlogged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='tab',
            field=models.IntegerField(default=30),
        ),
    ]
