# Generated by Django 3.2.6 on 2022-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0031_auto_20220407_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='extra_tab',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='number',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
