# Generated by Django 3.2.6 on 2022-04-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0033_auto_20220407_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='visitedInst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='visitedQue',
            field=models.BooleanField(default=False),
        ),
    ]
